#!/bin/bash
#
H=${1:-netbeisser.de}
S=1
P=80
DS=/var/tmp/php.txt # method req
set -o posix


cat >> /var/tmp/php.txt <<EOF
GET /CONTRIBUTING.md HTTP/1.1
GET /README.txt HTTP/1.1
GET /admin.php HTTP/1.1
GET /administrator/ HTTP/1.1
GET /components/com_mailto/views/sent/metadata.xml HTTP/1.1
GET /help.txt HTTP/1.1
GET /htaccess.txt HTTP/1.1
GET /joomla.xml HTTP/1.1
GET /libraries/joomla/filesystem/meta/language/en-GB/en-GB.lib_joomla_filesystem_patcher.ini HTTP/1.1
GET /license.txt HTTP/1.1
GET /phpunit.xml.dist HTTP/1.1
GET /readme.htm HTTP/1.1
GET /readme.html HTTP/1.1
GET /readme.txt HTTP/1.1
GET /web.config.txt HTTP/1.1
GET /wp-admin/css/colors-classic.css HTTP/1.1
GET /wp-admin/images/wp-logo-2x.png HTTP/1.1
GET /wp-admin/js/media-upload.dev.js HTTP/1.1
GET /wp-content/plugins/akismet/akismet.js HTTP/1.1
GET /wp-content/themes/classic/rtl.css HTTP/1.1
GET /wp-content/themes/twentyeleven/readme.txt HTTP/1.1
GET /wp-content/themes/twentyten/images/wordpress.png HTTP/1.1
GET /wp-content/themes/twentyten/style.css HTTP/1.1
GET /wp-includes/css/buttons.css HTTP/1.1
GET /wp-includes/js/scriptaculous/wp-scriptaculous.js HTTP/1.1
GET /wp-includes/js/tinymce/langs/wp-langs-en.js HTTP/1.1
GET /wp-includes/js/tinymce/wp-tinymce.js HTTP/1.1
GET /wp-login.php HTTP/1.1
PROPFIND /webdav/ HTTP/1.1
GET /phpmyadmin/main.php HTTP/1.1 
GET /services HTTP/1.1 
GET /phpMyAdmin/main.php HTTP/1.0 
GET /db/main.php HTTP/1.0 
GET /web/main.php HTTP/1.0 
GET /PMA/main.php HTTP/1.0 
GET /dbadmin/main.php HTTP/1.0 
GET /PMA2006/main.php HTTP/1.0 
GET /pma2006/main.php HTTP/1.0 
GET /sqlmanager/main.php HTTP/1.0 
GET /mysqlmanager/main.php HTTP/1.0 
GET /p/m/a/main.php HTTP/1.0 
GET /PMA2005/main.php HTTP/1.0 
GET /pma2005/main.php HTTP/1.0 
GET /phpmanager/main.php HTTP/1.0 
GET /php-myadmin/main.php HTTP/1.0 
GET /phpmy-admin/main.php HTTP/1.0 
GET /mysql/main.php HTTP/1.0 
GET /myadmin/main.php HTTP/1.0 
GET /webadmin/main.php HTTP/1.0 
GET /sqlweb/main.php HTTP/1.0 
GET /websql/main.php HTTP/1.0 
GET /webdb/main.php HTTP/1.0 
GET /mysqladmin/main.php HTTP/1.0 
GET /mysql-admin/main.php HTTP/1.0 
GET /phpmyadmin2/main.php HTTP/1.0 
GET /phpMyAdmin2/main.php HTTP/1.0 
GET /phpMyAdmin-2/main.php HTTP/1.0 
GET /php-my-admin/main.php HTTP/1.0 
GET /phpMyAdmin-2.2.3/main.php HTTP/1.0 
GET /phpMyAdmin-2.2.6/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.1/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.4/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.5-rc1/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.5-rc2/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.5/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.5-pl1/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.6-rc1/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.6-rc2/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.6/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.7/main.php HTTP/1.0 
GET /phpMyAdmin-2.5.7-pl1/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-alpha/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-alpha2/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-beta1/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-beta2/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-rc1/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-rc2/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-rc3/main.php HTTP/1.0 
GET /phpMyAdmin-2.6.0/main.php HTTP/1.0
GET /administrator/phpMyAdmin-2.6.0/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.0-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.0-pl2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.0-pl3/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1-rc2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1-pl2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.1-pl3/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.2-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.2-beta1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.2-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.3/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.3-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.3-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4-pl2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4-pl3/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4-pl4/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.6.4/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.7.0-beta1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.7.0-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.7.0-pl1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.7.0-pl2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.7.0/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0-beta1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0-rc2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0.1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0.2/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0.3/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.0.4/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.1-rc1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.1/main.php HTTP/1.0 
GET /administrator/phpMyAdmin-2.8.2/main.php HTTP/1.0 
GET /phpmyadmin/read_dump.phpmain.php HTTP/1.0 
GET /PMA/read_dump.phpmain.php HTTP/1.0 
GET /mysql/read_dump.phpmain.php HTTP/1.0 
GET /xampp/phpmyadmin/read_dump.phpmain.php HTTP/1.0 
GET /typo3/phpmyadmin/read_dump.phpmain.php HTTP/1.0 
GET /mysqladmin/read_dump.phpmain.php HTTP/1.0 
GET /admin/read_dump.phpmain.php HTTP/1.0 
GET /db/read_dump.phpmain.php HTTP/1.0 
GET /dbadmin/read_dump.phpmain.php HTTP/1.0 
GET /web/phpMyAdmin/read_dump.phpmain.php HTTP/1.0 
GET /admin/pma/read_dump.phpmain.php HTTP/1.0 
GET /admin/phpmyadmin/read_dump.phpmain.php HTTP/1.0 
GET /phpmyadmin2/read_dump.phpmain.php HTTP/1.0 
GET /phpmyadmin1/read_dump.phpmain.php HTTP/1.0 
GET /phpadmin/read_dump.phpmain.php HTTP/1.0 
GET /myadmin/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.2.3/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.5.6/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.5.7-pl1/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.6.0/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.6.0-pl3/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.6.1-pl3/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin-2.6.3-pl1/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin 2.6.4-pl4/read_dump.phpmain.php HTTP/1.0
GET /phpMyAdmin 2.7.0-beta1/read_dump.phpmain.php HTTP/1.0
GET /phpMyAdmin 2.7.0-rc1/read_dump.phpmain.php HTTP/1.0
GET /phpMyAdmin 2.7.0/read_dump.phpmain.php HTTP/1.0
GET /phpMyAdmin-2.6.4/read_dump.phpmain.php HTTP/1.0 
GET /phpMyAdmin 2.7.0-pl1/read_dump.phpmain.php HTTP/1.0
GET /phpMyAdmin-2.2.7-pl1/read_dump.phpmain.php HTTP/1.0 
GET http://119.160.244.97/config/isp_verify_user? HTTP/1.0 
GET http://heise.de/ HTTP/1.0 
POST /fun/index.php?!=1&topic=%3C?=hex(unique());?%3E%7C%3C?=$id;?%3E
GET /uploadify/uploadify.css HTTP/1.1
GET /uploadify.css HTTP/1.1
GET /admin/uploadify/uploadify.css HTTP/1.1
GET /public/js/uploadify/uploadify.css HTTP/1.1
GET /js/uploadify/uploadify.css HTTP/1.1
GET /include/lib/js/uploadify/uploadify.css HTTP/1.1
GET /data/plugin/uploadify/uploadify.css HTTP/1.1
GET /Public/uploadify/uploadify.css HTTP/1.1
GET /addons/uploadify/uploadify.css HTTP/1.1
GET /script/multiupload/uploadify.css HTTP/1.1
GET /setreuid+rc.sc HTTP/1.1
GET /inc/jquery/uploadify/uploadify.css HTTP/1.1
GET /general/weibo/javascript/LazyUploadify/uploadify.css HTTP/1.1
GET /uploadify/scripts/uploadify.css HTTP/1.1
GET /bocadmin/j/custom.js HTTP/1.1
GET /css/uploadify.css HTTP/1.1
GET /common/uploadify.css HTTP/1.1
GET /lib/uploadify.css HTTP/1.1
GET /admin/css/uploadify.css HTTP/1.1
GET /js/uploadify.css HTTP/1.1
GET /JS/jquery.uploadify-v2.1.0/uploadify.css HTTP/1.1
GET /js/Plug-in/jquery.uploadify/uploadify.css HTTP/1.1
GET /js/jquery.uploadify/uploadify.css HTTP/1.1
GET / HTTP/1.1
GET / HTTP/1.1
GET / HTTP/1.1
EOF

while read line; do
  sleep $S
{
   echo -e "$line\nHost: $H\nUser-Agent: Mozilla/5.1 (Wind0ws; U; Wind0ws ENTE 6.0; en-US)\nContent-Length: AAA\n\r\r\n"
}| nc -v $H $P
# make use of other peoples scans
done < $DS
